const menu = [
  {
    id: 1,
    title: "Circuit Bungalow",
    category: "ongoing",
    price: 15.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2020/08/32.jpg",
    desc: `Proposed Construction of Circuit Bungalow for National Youth Services Council at Nuwaraeliya.`,
  },
  {
    id: 2,
    title: "Two Stored Hospital",
    category: "local",
    price: 13.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2015/03/Picture54.jpg",
    desc: `Design and Construction of Proposed Two Storied Surgical Building at Base Hospital – Horan`,
  },
  {
    id: 3,
    title: "Hydro Power Project",
    category: "overseas",
    price: 6.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2018/09/Picture41.jpg",
    desc: `Construction of Mahoma Small Hydro Power Project.`,
  },
  {
    id: 4,
    title: "National Police Academy",
    category: "goverment",
    price: 20.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2015/03/Picture106.jpg",
    desc: `Construction of New Academic and Administrative Building for National Police Academy at Katana`,
  },
  {
    id: 5,
    title: "Materials Building",
    category: "ongoing",
    price: 22.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2020/08/35.jpg",
    desc: `Design and Build Basis Two Storied Steel Structure for Pharmaceuticals Raw Materials Building, Rathmalana`,
  },
  {
    id: 6,
    title: "Evergreen Solar, Inc",
    category: "private",
    price: 18.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2015/03/313.jpg",
    desc: `Evergreen Solar Inc. Solar Panel Manufacturing Plant uses Evergreen Solar Inc. String Ribbon™ wafer technology to fabricate their solar panels. `,
  },
  {
    id: 7,
    title: "Turner Nashville/Huntsville Main",
    category: "private",
    price: 8.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2015/07/Picture92.jpg",
    desc: `Turner is building a 7,000 square foot office building to serve as an office for Turner’s personnel in its Huntsville, Alabama location.`,
  },
  {
    id: 8,
    title: "Green Power",
    category: "ongoing",
    price: 12.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2020/08/33.jpg",
    desc: `Green Power Development and Energy Investment Program Part – 2 Lot A Trincomalee`,
  },
  {
    id: 9,
    title: "Sisecam A.S.",
    category: "private",
    price: 16.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2015/07/Picture114.jpg",
    desc: `he TR8 Flat Glass Factory serves as an expansion to existing plant facilities to provide the capability to produce colored flat glass.`,
  },

  {
    id: 10,
    title: "Rockefeller University",
    category: "private",
    price: 16.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2018/05/Picture46.jpg",
    desc: `The eight foot-wide bridge is supported by a single 90-foot tower and two 45-foot-tall tieback towers.`,
  },

  {
    id: 11,
    title: "RWIMI Project",
    category: "overseas",
    price: 6.99,
    img: "http://www.accessengsl.com/wp-content/uploads/2015/03/125.jpg",
    desc: `Construction of RWIMI Small Hydro Power Project`,
  },
];
export default menu;
